export const bmcCases = [
  { title: "Check clicking sign in as different user lands on enter mobile number", kind: "buyer-page" },
  { title: "Check user is able to login with OTP", kind: "buyer-page" },
  { title: "Check user is able to receive OTP on email", kind: "buyer-page" },
  { title: "Check invalid number displays an error message", kind: "buyer-page" },
  { title: "Check user navigates to message section from thank you page after enquiry", kind: "open-message-centre" },
  { title: "Navigate to Messages via Email Enquiry Notification", kind: "open-message-centre" },
  { title: "Navigate to Messages via Profile My Orders Send Message", kind: "open-message-centre" },
  { title: "Verify navigation to Message Module from header on all buyer pages", kind: "header-navigation" },
  { title: "Verify clicking Chat Now from My Orders opens supplier conversation in Messages", kind: "open-conversation" },
  { title: "Verify back to top CTA on buyer message centre", kind: "open-message-centre" },
  { title: "Verify giving rating in buyer message centre", kind: "open-conversation" },
  { title: "Verify landing from BuyerMy to buyer message centre", kind: "open-message-centre" },
  { title: "Verify open conversation in buyer message centre", kind: "open-conversation" },
  { title: "Verify search by city in buyer message centre", kind: "search-city" },
  { title: "Verify send attachment in buyer message centre", kind: "open-conversation" },
  { title: "Verify send message in buyer message centre", kind: "send-message" },
  { title: "Verify view details in buyer message centre", kind: "open-conversation" },
];
